wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714361879.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 19
      - 23
      - 37
      4: 3.8.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
args:
  desc: null
  value: Namespace(checkpoint_iterations=[29000, 60000], compute_cov3D_python=False,
    config_file='config/gaussian_dataset/train.json', convert_SHs_python=False, data_device='cuda',
    debug=False, debug_from=-1, densification_interval=100, densify_from_iter=500,
    densify_grad_threshold=0.0002, densify_iteration=[-1], densify_until_iter=100,
    detect_anomaly=False, eval=False, feature_lr=0.0025, images='images', ip='127.0.0.1',
    iterations=60000, lambda_dssim=0.2, loaded_iteration=30000, model_path='output/figurines_prune',
    n_views=100, num_classes=256, object_path='object_mask', opacity_lr=0.05, opacity_reset_interval=3000,
    percent_dense=0.01, port=6006, position_lr_delay_mult=0.01, position_lr_final=1.6e-06,
    position_lr_init=0.00016, position_lr_max_steps=30000, prune_decay=1, prune_iterations=[2],
    prune_type='opacity', quiet=False, random_init=False, reg3d_interval=5, reg3d_k=5,
    reg3d_lambda_val=2, reg3d_max_points=200000, reg3d_sample_size=1000, resolution=1,
    rotation_lr=0.001, save_iterations=[1000, 7000, 30000, 60000, 60000], scaling_lr=0.005,
    sh_degree=3, source_path='/scratch/jiasi_root/jiasi98/zxuechen/dataset_segmentation/data/figurines',
    start_checkpoint=None, start_pointcloud='/scratch/jiasi_root/jiasi98/zxuechen/dataset_segmentation/checkpoint/figurines',
    target_num=180000, test_iterations=[1000, 7000, 30000, 60000], train_split=True,
    use_wandb=True, v_pow=0.1, white_background=False)
